export enum FootballPosition {
  GOALKEEPER="GOALKEEPER",
  DEFENDER="DEFENDER",
  MIDFIELDER="MIDFIELDER",
  FORWARD="FORWARD",
  LEFT_BACK="LEFT_BACK",
  RIGHT_BACK="RIGHT_BACK",
  CENTER_BACK="CENTER_BACK",
  DEFENSIVE_MIDFIELDER="DEFENSIVE_MIDFIELDER",
  ATTACKING_MIDFIELDER="ATTACKING_MIDFIELDER",
  STRIKER="STRIKER",
  WINGER="WINGER"
}
